name: mobile_appraisal
description: "Aplikasi Front End Mobile Appraisal untuk Penilaian Agunan"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  google_fonts: ^6.2.1
  curved_navigation_bar: ^1.0.3
  skeletons: ^0.0.3
  flutter_animate: ^4.5.0
  http: ^1.2.1
  dartz: ^0.10.1
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.1
  shared_preferences: ^2.3.0
  awesome_snackbar_content: ^0.1.3
  dio: ^5.4.3+1
  animated_custom_dropdown: ^3.1.1
  buttons_tabbar: ^1.3.13
  uuid: ^4.4.2
  wolt_modal_sheet: ^0.10.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.5.0+1
  flutter_lints: ^4.0.0
  freezed: ^2.5.2
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/core/assets/
  integration:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  

