name: mobile_appraisal
description: "Aplikasi Front End Mobile Appraisal untuk Penilaian Agunan"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  google_fonts: ^6.2.1
  curved_navigation_bar: ^1.0.3
  skeletons: ^0.0.3

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.5.0+1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/core/assets/
  integration:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  

